.TH POWERBG "1" "2021" "INFO MONO" "User Commands"
.SH NAME
Powerbg \- #TODO
.SH SYNOPSIS
.B powerbg
.SH DESCRIPTION
#TODO.
.SH ENVIRONMENT VARIABLES
\fBPOWERBG_LEFTEND_OUTER\fR
Set .
\fBPOWERBG_LEFTEND_INNER\fR
Set .
\fBPOWERBG_RIGHTEND_OUTER\fR
Set .
\fBPOWERBG_RIGHTEND_INNER\fR
Set .
\fBPOWERBG_SEPARATOR_LEFT\fR
Set .
\fBPOWERBG_SEPARATOR_RIGHT\fR
Set .
\fBPOWERBG_SEPARATOR_SAME\fR
Set .
.SH REPORTING BUGS
Report bugs to https://github.com/info-mono/powerbg/issues
