.TH POWERBG "1" "2021" "INFO MONO" "User Commands"
.SH NAME
PowerBG \- Add background color to info line like Powerline
.SH SYNOPSIS
.B powerbg COLOR STRING COLOR STRING COLOR STRING ...
.SH DESCRIPTION
PowerBG is a tool that add to color string's background like Powerline
.SH ENVIRONMENT VARIABLES
\fBPOWERBG_LEFTEND_OUTER\fR
Set left end outer string.
\fBPOWERBG_LEFTEND_INNER\fR
Set left end inner string.
\fBPOWERBG_RIGHTEND_OUTER\fR
Set right end outer string.
\fBPOWERBG_RIGHTEND_INNER\fR
Set right end inner string.
\fBPOWERBG_SEPARATOR_LEFT\fR
Set separator left string.
\fBPOWERBG_SEPARATOR_RIGHT\fR
Set separator right string.
\fBPOWERBG_SEPARATOR_SAME\fR
Set separator string to use when when separating two elements with the same color.
.SH REPORTING BUGS
Report bugs to https://github.com/info-mono/powerbg/issues
